# Build the di-operator binary

# Use distroless as minimal base image to package the di-operator binary
# Refer to https://github.com/GoogleContainerTools/distroless for more details
FROM redhat/ubi8:latest as di-operator
LABEL maintainer="opendilab.contact@gmail.com"
RUN ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime
WORKDIR /
COPY ./bin/di-operator  .

ENTRYPOINT ["/di-operator"]

FROM redhat/ubi8:latest as di-webhook
LABEL maintainer="opendilab.contact@gmail.com"
RUN ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime
WORKDIR /
COPY ./bin/di-webhook .

ENTRYPOINT ["/di-webhook"]

FROM redhat/ubi8:latest as di-server
LABEL maintainer="opendilab.contact@gmail.com"
RUN ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime
WORKDIR /
COPY ./bin/di-server .

ENTRYPOINT ["/di-server"]
