# Build the di-orchestrator binary

# Use distroless as minimal base image to package the di-orchestrator binary
# Refer to https://github.com/GoogleContainerTools/distroless for more details
FROM redhat/ubi8:latest as di-orchestrator
LABEL maintainer="opendilab.contact@gmail.com"
RUN ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime
WORKDIR /
COPY ./bin/di-orchestrator  .

ENTRYPOINT ["/di-orchestrator"]

