apiVersion: apps/v1
kind: Deployment
metadata:
  name: di-server
  namespace: di-system
  labels:
    control-plane: di-server
spec:
  selector:
    matchLabels:
      control-plane: di-server
  replicas: 1
  template:
    metadata:
      labels:
        control-plane: di-server
    spec:
      containers:
      - command:
        - /di-orchestrator
        - server
        args:
        - --server-bind-address=:8080
        - --gpu-alloc-policy=simple
        image: registry.sensetime.com/cloudnative4ai/di-orchestrator:v0.3.0-51ca9ef7
        imagePullPolicy: Always
        name: server
        securityContext:
          allowPrivilegeEscalation: false
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 20
        resources:
          limits:
            cpu: 100m
            memory: 500Mi
          requests:
            cpu: 100m
            memory: 500Mi
      terminationGracePeriodSeconds: 10
