apiVersion: apps/v1
kind: Deployment
metadata:
  name: di-server
  labels:
    control-plane: di-server
spec:
  selector:
    matchLabels:
      control-plane: di-server
  replicas: 1
  template:
    metadata:
      labels:
        control-plane: di-server
    spec:
      containers:
      - command:
        - /di-orchestrator
        - server
        args:
        - --zap-devel=true
        - --server-bind-address=:8081
        image: opendilab/di-orchestrator:v1.0.0
        imagePullPolicy: Always
        name: server
        envFrom:
        - configMapRef:
            name: di-config
        securityContext:
          allowPrivilegeEscalation: false
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 20
        resources:
          limits:
            cpu: 100m
            memory: 500Mi
          requests:
            cpu: 100m
            memory: 500Mi
      terminationGracePeriodSeconds: 10
