apiVersion: apps/v1
kind: Deployment
metadata:
  name: nervex-server
  namespace: nervex-system
  labels:
    control-plane: nervex-server
spec:
  selector:
    matchLabels:
      control-plane: nervex-server
  replicas: 1
  template:
    metadata:
      labels:
        control-plane: nervex-server
    spec:
      containers:
      - command:
        - /nervex-server
        image: registry.sensetime.com/cloudnative4ai/nervex-server:v0.0.1-alpha.0-f819fc68
        imagePullPolicy: Always
        name: server
        securityContext:
          allowPrivilegeEscalation: false
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 20
        resources:
          limits:
            cpu: 100m
            memory: 30Mi
          requests:
            cpu: 100m
            memory: 20Mi
      terminationGracePeriodSeconds: 10

---
apiVersion: v1
kind: Service
metadata:
  name: nervex-server
  namespace: nervex-system
spec:
  selector:
    control-plane: nervex-server
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
