apiVersion: diengine.opendilab.org/v1alpha1
kind: AggregatorConfig
metadata:
  name: aggregator-config
  namespace: di-system
spec:
  aggregator:
    template:
      spec:
        containers:
        - name: shell
          image: busybox
          imagePullPolicy: IfNotPresent
          securityContext:
            capabilities:
              add:
              - SYS_PTRACE
          stdin: true
          tty: true
        - name: di-container
          image: registry.sensetime.com/cloudnative4ai/ding:v0.1.0-75c41277
          imagePullPolicy: Always
          env:
          - name: PYTHONUNBUFFERED
            value: "1"
          resources:
            requests:
              cpu: 3
              memory: "10Gi"
            limits:
              cpu: 3
              memory: "10Gi"
          command: ["/bin/bash", "-c",]
          args:
          - |
            # if code has been changed in the mount path, we have to reinstall  cli
            # pip install --no-cache-dir -e .;
            # pip install --no-cache-dir -e .[common_env]
            
            ding -m dist --module learner_aggregator
          ports:
          - name: di-port
            containerPort: 22270