
---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: nervex-mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: nervex-webhook-service
      namespace: nervex-system
      path: /mutate-nervex-sensetime-com-v1alpha1-nervexjob
  failurePolicy: Fail
  name: mnervexjob.kb.io
  rules:
  - apiGroups:
    - nervex.sensetime.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - nervexjobs
  sideEffects: None

---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: nervex-validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: nervex-webhook-service
      namespace: nervex-system
      path: /validate-nervex-sensetime-com-v1alpha1-nervexjob
  failurePolicy: Fail
  name: vnervexjob.kb.io
  rules:
  - apiGroups:
    - nervex.sensetime.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - nervexjobs
  sideEffects: None
