
---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: di-mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: di-webhook-service
      namespace: di-system
      path: /mutate-diengine-sensetime-com-v1alpha1-dijob
  failurePolicy: Fail
  name: mdijob.kb.io
  rules:
  - apiGroups:
    - diengine.sensetime.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - dijobs
  sideEffects: None

---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: di-validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: di-webhook-service
      namespace: di-system
      path: /validate-diengine-sensetime-com-v1alpha1-dijob
  failurePolicy: Fail
  name: vdijob.kb.io
  rules:
  - apiGroups:
    - diengine.sensetime.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - dijobs
  sideEffects: None
