# permissions for end users to view actorleanerconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: actorleanerconfig-viewer-role
rules:
- apiGroups:
  - nervex.sensetime.com
  resources:
  - actorleanerconfigs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - nervex.sensetime.com
  resources:
  - actorleanerconfigs/status
  verbs:
  - get
