apiVersion: v1
kind: Service
metadata:
  labels:
    control-plane: nervex-operator
  name: nervex-operator-metrics-service
  namespace: nervex-system
spec:
  ports:
  - name: https
    port: 8443
    targetPort: 8080
  selector:
    control-plane: nervex-operator
