apiVersion: v1
kind: Service
metadata:
  labels:
    control-plane: di-operator
  name: di-operator-metrics-service
  namespace: di-system
spec:
  ports:
  - name: https
    port: 8443
    targetPort: 8080
  selector:
    control-plane: di-operator
