# permissions for end users to edit nervexjobs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nervexjob-editor-role
rules:
- apiGroups:
  - nervex.sensetime.com
  resources:
  - nervexjobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - nervex.sensetime.com
  resources:
  - nervexjobs/status
  verbs:
  - get
