# permissions for end users to view nervexjobs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nervexjob-viewer-role
rules:
- apiGroups:
  - nervex.sensetime.com
  resources:
  - nervexjobs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - nervex.sensetime.com
  resources:
  - nervexjobs/status
  verbs:
  - get
