
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: di-operator-cluster-role
rules:
- apiGroups:
  - ""
  resources:
  - events
  - pods
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - namespaces
  - nodes
  verbs:
  - get
  - list
- apiGroups:
  - diengine.sensetime.com
  resources:
  - aggregatorconfigs
  - dijobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - diengine.sensetime.com
  resources:
  - aggregatorconfigs/finalizers
  - dijobs/finalizers
  verbs:
  - update
- apiGroups:
  - diengine.sensetime.com
  resources:
  - aggregatorconfigs/status
  - dijobs/status
  verbs:
  - get
  - patch
  - update
