
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - nervex.sensetime.com
  resources:
  - nervexjobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - nervex.sensetime.com
  resources:
  - nervexjobs/finalizers
  verbs:
  - update
- apiGroups:
  - nervex.sensetime.com
  resources:
  - nervexjobs/status
  verbs:
  - get
  - patch
  - update
