# The following patch enables a conversion webhook for the CRD
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: nervexjobs.nervex.sensetime.com
spec:
  conversion:
    strategy: Webhook
    webhook:
      clientConfig:
        service:
          namespace: $(SERVICE_NAMESPACE)
          name: $(SERVICE_NAME)
          path: /mutate-nervex-sensetime-com-v1alpha1-nervexjob
      conversionReviewVersions:
      - "v1"
      - "v1beta1"
