apiVersion: diengine.opendilab.org/v2alpha1
kind: DIJob
metadata:
  name: job-with-tasks
  # generateName: gobigger-test-
spec:
  priority: "normal"  # 表示job的优先级，保留字段，调度中或许可以用到
  backoffLimit: 0  # 表示job允许的最大重启次数，可以为nil，表示无限重启；默认为3，可以通过status.restarts看到实际重启次数
  cleanPodPolicy: "Running"  # 表示job运行完成之后，如何处理worker pods。Running表示job完成后删除所有还在Running的pods
  preemptible: false  # 表示job是否允许被抢占，调度中对job资源改动之后涉及到抢占操作。目前只能设置为false
  volumes:
  - name: cache-volume
    emptyDir:
      medium: Memory
      sizeLimit: 128Mi
  - name: config-py
    configMap:
      name: config-py
  tasks:
  - replicas: 1
    name: "learner"
    type: learner
    template:
      spec:
        containers:
        - name: di-container
          image: opendilab/ding:v0.3.1-dist
          imagePullPolicy: IfNotPresent
          env:
          - name: NCCL_DEBUG
            value: "INFO"
          command: ["/bin/bash", "-c",]
          args:
          - |
            cat /etc/config/config.py
            ditask --labels learner \
            --package . \
            --main dizoo.atari.example.atari_dqn_dist.main \
            --parallel-workers 2 \
            --topology mesh \
            --platform k8s 
          volumeMounts:
          - name: cache-volume
            mountPath: /dev/shm
          - name: config-py
            mountPath: /etc/config
        restartPolicy: Never
  - replicas: 1
    name: "evaluator"
    type: evaluator
    template:
      spec:
        containers:
        - name: di-container
          image: opendilab/ding:v0.3.1-dist
          imagePullPolicy: IfNotPresent
          env:
          - name: NCCL_DEBUG
            value: "INFO"
          command: ["/bin/bash", "-c",]
          args:
          - |
            cat /etc/config/config.py
            ditask --labels evaluator \
            --package . \
            --main dizoo.atari.example.atari_dqn_dist.main \
            --parallel-workers 2 \
            --topology mesh \
            --platform k8s 
          volumeMounts:
          - name: cache-volume
            mountPath: /dev/shm
          - name: config-py
            mountPath: /etc/config
        restartPolicy: Never
  - replicas: 1
    name: "collector"
    type: collector
    template:
      spec:
        containers:
        - name: di-container
          image: opendilab/ding:v0.3.1-dist
          imagePullPolicy: IfNotPresent
          env:
          - name: NCCL_DEBUG
            value: "INFO"
          command: ["/bin/bash", "-c",]
          args:
          - |
            cat /etc/config/config.py
            ditask --labels collector \
            --package . \
            --main dizoo.atari.example.atari_dqn_dist.main \
            --parallel-workers 2 \
            --topology mesh \
            --platform k8s 
          volumeMounts:
          - name: cache-volume
            mountPath: /dev/shm
          - name: config-py
            mountPath: /etc/config
        restartPolicy: Never
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: config-py
data:
  config.py: |
    from easydict import EasyDict

    cartpole_dqn_config = dict(
        exp_name='cartpole_dqn_seed0',
        env=dict(
            collector_env_num=8,
            evaluator_env_num=5,
            n_evaluator_episode=5,
            stop_value=195,
            replay_path='cartpole_dqn_seed0/video',
        ),
    ...
    )