apiVersion: diengine.opendilab.org/v1alpha2
kind: DIJob
metadata:
  name: gobigger-test
  # generateName: gobigger-test-
spec:
  group: "xxx"  # 标记job所属的group
  priority: "normal"  # 表示job的优先级，保留字段，调度中或许可以用到
  cleanPodPolicy: "None"  # 表示job运行完成之后，如何处理worker pods
  preemptible: false  # 表示job是否允许被抢占，调度中对job资源改动之后涉及到抢占操作
  minReplicas: 2
  maxReplicas: 5
  engineFields:
    topology: "star"  # 表示workers之间的拓扑连接
    parallelWorkers: 2  # 表示每个worker中启动的parallel workers数目
  template:
    spec:
      containers:
      - name: di-container
        image: registry.sensetime.com/cloudnative4ai/ding:ditask-example
        imagePullPolicy: Always
        env:
        - name: PYTHONUNBUFFERED
          value: "1"
        resources:
          requests:
            cpu: 6
            memory: "10Gi"
          limits:
            cpu: 6
            memory: "10Gi"
        command: ["/bin/bash", "-c",]
        args:
        - |
          ditask --package dibench --main diengine.pendulum_sac_main.main_entry --protocol tcp $DI_PARALLEL_WORKERS_ARG $DI_PORTS_ARG $DI_NODE_IDS_ARG $DI_ATTACHED_NODES_ARG
        volumeMounts:
        - name: work-dir
          mountPath: /data/nfs/ding
      volumes:
      - name: cache-volume
        emptyDir:
          medium: Memory
          sizeLimit: 128Mi
      - name: work-dir
        hostPath:
          path: /data/nfs/ding