apiVersion: diengine.opendilab.org/v2alpha1
kind: DIJob
metadata:
  name: serial-test
  # generateName: serial-test-
spec:
  priority: "normal"  # 表示job的优先级，保留字段，调度中或许可以用到
  backoffLimit: 0  # 重启次数，可以为nil，表示无限重启；默认为3
  cleanPodPolicy: "Running"  # 表示job运行完成之后，如何处理worker pods
  preemptible: false  # 表示job是否允许被抢占，调度中对job资源改动之后涉及到抢占操作
  volumes:
  - name: cache-volume
    emptyDir:
      medium: Memory
      sizeLimit: 128Mi
  tasks:
  - replicas: 1
    name: serial
    type: none
    template:
      spec:
        containers:
        - name: di-container
          image: opendilab/ding:nightly
          imagePullPolicy: Always
          env:
          - name: PYTHONUNBUFFERED
            value: "1"
          command: ["/bin/bash", "-c",]
          args:
          - |
            ding -m serial -c dizoo/classic_control/cartpole/config/cartpole_dqn_config.py -s 0
          volumeMounts:
          - name: cache-volume
            mountPath: /dev/shm
      
