apiVersion: diengine.opendilab.org/v2alpha1
kind: DIJob
metadata:
  name: gobigger-test
  # generateName: gobigger-test-
spec:
  group: "xxx"  
  priority: "normal"  
  cleanPodPolicy: "None"  
  preemptible: false  
  minReplicas: 2
  maxReplicas: 5
  engineFields:
    topology: "star"  
    parallelWorkers: 2  
  template:
    spec:
      containers:
      - name: di-container
        image: opendilab/ding:ditask-example
        imagePullPolicy: Always
        env:
        - name: PYTHONUNBUFFERED
          value: "1"
        resources:
          requests:
            cpu: 6
            memory: "10Gi"
          limits:
            cpu: 6
            memory: "10Gi"
        command: ["/bin/bash", "-c",]
        args:
        - |
          ditask --package dibench --main diengine.pendulum_sac_main.main_entry --protocol tcp $DI_PARALLEL_WORKERS_ARG $DI_PORTS_ARG $DI_NODE_IDS_ARG $DI_ATTACHED_NODES_ARG
        volumeMounts:
        - name: work-dir
          mountPath: /data/nfs/ding
      volumes:
      - name: cache-volume
        emptyDir:
          medium: Memory
          sizeLimit: 128Mi
      - name: work-dir
        hostPath:
          path: /data/nfs/ding