apiVersion: nervex.sensetime.com/v1alpha1
kind: NervexJob
metadata:
  name: nervexjob-example
spec:
  group: xxx
  priorityClassName: default
  coordinator:
    template:
      spec:
        containers:
        - name: coordinator
          image: registry.sensetime.com/cloudnative4ai/nervex-parallel-linklink-migration:v0.10
          imagePullPolicy: Always
          env:
          - name: LC_ALL
            value: "en_US.utf-8"
          - name: LANG
            value: "en_US.utf-8"
          - name: NCCL_SHM_DISABLE
            value: "1"
          command: ["/bin/bash", "-c",]
          args:
          - >
            cd /nfs/lijianwen/test_atari/test3;
            python3 -u -c 'import nervex.entry.parallel_entry as pe; pe.launch_coordinator(filename="atari_impala_default_config.py.pkl")';
            while true; do sleep 30; done;
          ports:
          - containerPort: 22273
          resources:
            requests:
              cpu: 2
              memory: 5Gi
            limits:
              cpu: 2
              memory: 5Gi
          volumeMounts:
          - name: config
            mountPath: /data/nervex
        volumes:
        - name: config
          nfs:
            path: /data/nfs/nervex
            server: 10.152.197.14