apiVersion: nervex.sensetime.com/v1alpha1
kind: ActorLearnerConfig
metadata:
  name: nervexjob-actor-learner-config
spec:
  actor:
    template:
      spec:
        containers:
        - name: actor
          image: registry.sensetime.com/cloudnative4ai/mock_nervex:v0.0.1
          imagePullPolicy: IfNotPresent
          command: ["/bin/bash", "-c",]
          args: ["until ping -c 1 $HOSTNAME.default ; do sleep 1 ; done ; sleep 5; python3 -u main.py actor -l $HOSTNAME.default -p $ACTOR_PORT"]
          ports:
          - name: actor
            containerPort: 80
  learner:
    template:
      spec:
        containers:
        - name: learner
          image: registry.sensetime.com/cloudnative4ai/mock_nervex:v0.0.1
          imagePullPolicy: IfNotPresent
          command: ["/bin/bash", "-c",]
          args: ["until ping -c 1 $HOSTNAME.default ; do sleep 1 ; done ; sleep 5; python3 -u main.py learner -l $HOSTNAME.default -p $LEARNER_PORT"]
          ports:
          - name: learner
            containerPort: 80
  aggregator:
    template:
      spec:
        containers:
        - name: learner
          image: registry.sensetime.com/cloudnative4ai/nginx:latest
          ports:
          - name: aggregator
            containerPort: 80
status:
  actors:
    total: 4
    active: 3
    idle: 1
  learners:
    total: 5
    active: 5
    idle: 0
