apiVersion: nervex.sensetime.com/v1alpha1
kind: AggregatorConfig
metadata:
  name: aggregator-config
spec:
  aggregator:
    template:
      spec:
        containers:
        - name: aggregator
          image: registry.sensetime.com/cloudnative4ai/nervex-parallel-linklink-migration:v0.10
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 2
              memory: 5Gi
            limits:
              cpu: 2
              memory: 5Gi
          env:
          - name: LC_ALL
            value: "en_US.utf-8"
          - name: LANG
            value: "en_US.utf-8"
          - name: NCCL_SHM_DISABLE
            value: "1"
          command: ["/bin/bash", "-c",]
          args:
          - >
            until curl $HOSTNAME:22279 &>/dev/null ; do sleep 1 ; done ; echo succeed;
            until curl $HOSTNAME:22279 &>/dev/null ; do sleep 1 ; done ; echo succeed;
            cd /data/nervex/test_atari/test3;
            python3 -u -c 'import os; import nervex.entry.parallel_entry as pe; pe.launch_learner_aggregator(filename="atari_impala_default_config.py.pkl", name="aggregator{}".format(os.environ["HOSTNAME"].split("-")[-1]) )';
          ports:
          - name: aggregator
            containerPort: 22272
          volumeMounts:
          - name: config
            mountPath: /data/nervex
        volumes:
        - name: config
          nfs:
            path: /data/nfs/nervex
            server: 10.152.197.14
status:
  actors:
    total: 4
    active: 3
    idle: 1
  learners:
    total: 5
    active: 5
    idle: 0