apiVersion: nervex.sensetime.com/v1alpha1
kind: NerveXJob
metadata:
  name: nervexjob-example-1
spec:
  group: xxx
  priorityClassName: default
  coordinator:
    template:
      spec:
        containers:
        - name: coordinator
          image: registry.sensetime.com/cloudnative4ai/nervex-mock:v0.0.4
          imagePullPolicy: IfNotPresent
          command: ["/bin/bash", "-c",]
          args: ["python3 -u main.py coordinator -l $HOSTNAME -p $COORDINATOR_PORT"]
          # args: ["sleep 3600"]
  collector:
    template:
      spec:
        containers:
        - name: collector
          image: registry.sensetime.com/cloudnative4ai/nervex-mock:v0.0.4
          imagePullPolicy: IfNotPresent
          command: ["/bin/bash", "-c",]
          args: ["until ping -c 1 $HOSTNAME.default ; do sleep 1 ; done ; sleep 5; python3 -u main.py actor -l $HOSTNAME.default -p $ACTOR_PORT"]
          ports:
          - name: collector
            containerPort: 80
  learner:
    template:
      spec:
        containers:
        - name: learner
          image: registry.sensetime.com/cloudnative4ai/nervex-mock:v0.0.4
          imagePullPolicy: IfNotPresent
          command: ["/bin/bash", "-c",]
          args: ["until ping -c 1 $HOSTNAME.default ; do sleep 1 ; done ; sleep 5; python3 -u main.py learner -l $HOSTNAME.default -p $LEARNER_PORT"]
          ports:
          - name: learner
            containerPort: 80
