apiVersion: nervex.sensetime.com/v1alpha1
kind: AggregatorConfig
metadata:
  name: aggregator-config
  namespace: nervex-system
spec:
  aggregator:
    template:
      spec:
        # nodeSelector:
        #   kubernetes.io/hostname: "liqingping-gpu.novalocal"
        containers:
        - name: aggregator
          image: registry.sensetime.com/cloudnative4ai/nervex:v0.0.4-torch1.4-cuda10.1-cudnn7-devel-987bacf7
          imagePullPolicy: Always
          env:
          - name: LC_ALL
            value: "en_US.utf-8"
          - name: LANG
            value: "en_US.utf-8"
          - name: PYTHONUNBUFFERED
            value: "1"
          resources:
            requests:
              cpu: 3
              memory: "10Gi"
            limits:
              cpu: 3
              memory: "10Gi"
          command: ["/bin/bash", "-c",]
          args:
          - |
            # if code has been changed in the mount path, we have to reinstall nervex cli
            # pip install --no-cache-dir -e .;
            # pip install --no-cache-dir -e .[common_env]
            
            nervex -m dist --module config -p k8s -c app_zoo/atari/config/parallel/qbert_dqn_config_k8s.py -s 0;
            nervex -m dist --module learner_aggregator -c app_zoo/atari/config/parallel/qbert_dqn_config_k8s.py.pkl -s 0
          ports:
          - name: aggregator
            containerPort: 22270