apiVersion: nervex.sensetime.com/v1alpha1
kind: ActorLearnerConfig
metadata:
  name: nervexjob-actor-learner-config
spec:
  actor:
    template:
      spec:
        containers:
        - name: actor
          image: registry.sensetime.com/cloudnative4ai/nervex-mock:v0.0.3
          imagePullPolicy: Always
          command: ["/bin/bash", "-c",]
          args: ["until ping -c 1 $HOSTNAME.default ; do sleep 1 ; done ; sleep 5; python3 -u main.py actor -l $HOSTNAME.default -p $ACTOR_PORT"]
          ports:
          - name: actor
            containerPort: 80
  learner:
    template:
      spec:
        containers:
        - name: learner
          image: registry.sensetime.com/cloudnative4ai/nervex-mock:v0.0.3
          imagePullPolicy: Always
          command: ["/bin/bash", "-c",]
          args: ["until ping -c 1 $HOSTNAME.default ; do sleep 1 ; done ; sleep 5; python3 -u main.py learner -l $HOSTNAME.default -p $LEARNER_PORT"]
          ports:
          - name: learner
            containerPort: 80
  aggregator:
    template:
      spec:
        containers:
        - name: aggregator
          image: registry.sensetime.com/cloudnative4ai/nervex-mock:v0.0.3
          imagePullPolicy: Always
          command: ["/bin/bash", "-c",]
          args: ["until ping -c 1 $HOSTNAME.default ; do sleep 1 ; done ; sleep 5; python3 -u main.py aggregator -sl $HOSTNAME.default -sp $AGGREGATOR_PORT -sl $HOSTNAME.default -ml $HOSTNAME.default -mp 81"]
          ports:
          - name: actor
            containerPort: 80
