apiVersion: nervex.sensetime.com/v1alpha1
kind: NerveXJob
metadata:
  name: nervexjob-example-1
spec:
  group: xxx
  priorityClassName: default
  coordinator:
    template:
      spec:
        containers:
        - name: coordinator
          image: registry.sensetime.com/cloudnative4ai/nervex-mock:v0.0.3
          imagePullPolicy: Always
          command: ["/bin/bash", "-c",]
          args: ["python3 -u main.py coordinator -l $HOSTNAME -p $COORDINATOR_PORT"]
          # args: ["sleep 3600"]
