apiVersion: nervex.sensetime.com/v1alpha1
kind: ActorLearnerConfig
metadata:
  name: nervexjob-actor-learner-config
spec:
  collector:
    template:
      spec:
        containers:
        - name: collector
          image: registry.sensetime.com/cloudnative4ai/nervex-mock:v0.0.4
          imagePullPolicy: Always
          command: ["/bin/bash", "-c",]
          args: ["until ping -c 1 $HOSTNAME.default ; do sleep 1 ; done ; sleep 10; python3 -u main.py collector -l $HOSTNAME.default -p $COLLECTOR_PORT"]
          ports:
          - name: collector
            containerPort: 80
  learner:
    template:
      spec:
        containers:
        - name: learner
          image: registry.sensetime.com/cloudnative4ai/nervex-mock:v0.0.4
          imagePullPolicy: Always
          command: ["/bin/bash", "-c",]
          args: ["until ping -c 1 $HOSTNAME.default ; do sleep 1 ; done ; sleep 10; python3 -u main.py learner -l $HOSTNAME.default -p $LEARNER_PORT"]
          ports:
          - name: learner
            containerPort: 80
  aggregator:
    template:
      spec:
        containers:
        - name: aggregator
          image: registry.sensetime.com/cloudnative4ai/nervex-mock:v0.0.4
          imagePullPolicy: Always
          command: ["/bin/bash", "-c",]
          args: ["until ping -c 1 $HOSTNAME.default ; do sleep 1 ; done ; sleep 10; python3 -u main.py aggregator -sl $HOSTNAME.default -sp $AGGREGATOR_PORT -sl $HOSTNAME.default -ml $HOSTNAME.default -mp 81"]
          ports:
          - name: aggregator
            containerPort: 80
