apiVersion: nervex.sensetime.com/v1alpha1
kind: AggregatorConfig
metadata:
  name: aggregator-config
spec:
  aggregator:
    template:
      spec:
        containers:
        - name: aggregator
          image: registry.sensetime.com/cloudnative4ai/nginx:latest
          ports:
          - name: aggregator
            containerPort: 80
status:
  actors:
    total: 4
    active: 3
    idle: 1
  learners:
    total: 5
    active: 5
    idle: 0
