apiVersion: nervex.sensetime.com/v1alpha1
kind: ActorLearnerConfig
metadata:
  name: nervexjob-actor-learner-config
spec:
  actor:
    template:
      spec:
        containers:
        - name: actor
          image: registry.sensetime.com/cloudnative4ai/nginx:latest
          ports:
          - name: actor-port
            containerPort: 80
  learner:
    template:
      spec:
        containers:
        - name: learner
          image: registry.sensetime.com/cloudnative4ai/nginx:latest
          ports:
          - name: learner-port
            containerPort: 80
  aggregator:
    template:
      spec:
        containers:
        - name: learner
          image: registry.sensetime.com/cloudnative4ai/nginx:latest
          ports:
          - name: aggr-port
            containerPort: 80
status:
  actors:
    total: 4
    active: 3
    idle: 1
  learners:
    total: 5
    active: 5
    idle: 0
