apiVersion: diengine.opendilab.org/v1alpha1
kind: AggregatorConfig
metadata:
  name: aggregator-config
  namespace: di-system
spec:
  aggregator:
    template:
      spec:
        containers:
        - name: di-container
          image: opendilab/di-mock:v0.0.5
          imagePullPolicy: IfNotPresent
          command: ["/bin/bash", "-c",]
          args: ["until ping -c 1 $HOSTNAME.default ; do sleep 1 ; done ; sleep 5; python3 -u main.py aggregator -sl $HOSTNAME.default -sp $AGGREGATOR_PORT -sl $HOSTNAME.default -ml $HOSTNAME.default -mp 81"]
          ports:
          - name: di-port
            containerPort: 80
