name: Go

on:
  - push
  - pull_request

jobs:

  # lint: 
  #   runs-on: 

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Build
      run: go build -v ./...

    - name: Test
      shell: bash
      run: |
        # download etcd to bootstrap test environment
        curl -L https://github.com/kubernetes-sigs/kubebuilder/releases/download/v2.3.2/kubebuilder_2.3.2_linux_amd64.tar.gz  | tar -xz -C /tmp/
        mv /tmp/kubebuilder_2.3.2_linux_amd64 /tmp/kubebuilder
        export KUBEBUILDER_ASSETS=/tmp/kubebuilder/bin
        make test